name: osef
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy=1.21.2
  - scipy=1.7.1
  - pandas=1.3.3
  - matplotlib=3.4.3
  - scikit-learn=0.24.2
  - jupyter
  - ipython
  - notebook
  - pip
  - pip:
    - nolds==0.5.2
    - plotly==5.3.1
    - h5py==3.6.0
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - black==21.9b0
    - sphinx==4.2.0
    - sphinx-rtd-theme==1.0.0
